[package]
name = "authy"
version = "0.1.0"
edition = "2021"

[dependencies]
proto_stub = { path = "../proto_stub" }
tokio.workspace = true 
tonic.workspace = true
tonic-reflection.workspace = true
serde.workspace = true
